export const teamData = [
  {
    name: "Abul Hasem",
    position: "CEO & Founder",
    img: "/assets/person.png",
    facebook: "",
    instgram: "",
    twitter: "",
  },
  {
    name: "maruf hassan",
    position: "FRONTEND TEAM LEADER",
    img: "/assets/person.png",
    facebook: "",
    instgram: "",
    twitter: "",
  },
  {
    name: "iMRAN HOSSAIN",
    position: "BACKEND TEAM LEADER",
    img: "/assets/person.png",
    facebook: "",
    instgram: "",
    twitter: "",
  },
  {
    name: "MIZANUR RAHMAN",
    position: "SENIOUR SOFTWARE ENGINEER",
    img: "/assets/person.png",
    facebook: "",
    instgram: "",
    twitter: "",
  },
  {
    name: "Abul Hasem",
    position: "CEO & Founder",
    img: "/assets/person.png",
    facebook: "",
    instgram: "",
    twitter: "",
  },
  {
    name: "maruf hassan",
    position: "FRONTEND TEAM LEADER",
    img: "/assets/person.png",
    facebook: "",
    instgram: "",
    twitter: "",
  },
  {
    name: "iMRAN HOSSAIN",
    position: "BACKEND TEAM LEADER",
    img: "/assets/person.png",
    facebook: "",
    instgram: "",
    twitter: "",
  },
  {
    name: "MIZANUR RAHMAN",
    position: "SENIOUR SOFTWARE ENGINEER",
    img: "/assets/person.png",
    facebook: "",
    instgram: "",
    twitter: "",
  },
  {
    name: "Abul Hasem",
    position: "CEO & Founder",
    img: "/assets/person.png",
    facebook: "",
    instgram: "",
    twitter: "",
  },
  {
    name: "maruf hassan",
    position: "FRONTEND TEAM LEADER",
    img: "/assets/person.png",
    facebook: "",
    instgram: "",
    twitter: "",
  },
  {
    name: "iMRAN HOSSAIN",
    position: "BACKEND TEAM LEADER",
    img: "/assets/person.png",
    facebook: "",
    instgram: "",
    twitter: "",
  },
  {
    name: "MIZANUR RAHMAN",
    position: "SENIOUR SOFTWARE ENGINEER",
    img: "/assets/person.png",
    facebook: "",
    instgram: "",
    twitter: "",
  },
];
